baseURL = 'https://crisfe.im/'
languageCode = 'en-us'
title = 'crife.im'


[module]
[[module.mounts]]
source = 'content'
target = 'content'
excludeFiles = ['node_modules/a.*']

[markup.tableOfContents]
startLevel = 2
endLevel = 2


[params]
description = "Technical blog and projects by Cristian Rojas. AI, development, and custom tools."

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = true
style = "nord"
